language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO=Django==1.4
  - DJANGO=Django==1.5
  - DJANGO=Django==1.6

install:
  - pip install -q $DJANGO

script:
  - PYTHONPATH=$PYTHONPATH:$PWD django-admin.py test axes --settings=axes.test_settings

matrix:
    exclude:
        - python: 3.3
          env: DJANGO=Django==1.4
